### ISSUE TITLE
Should CreateRegExpStringIterator abstract operation list arguments in a signature?

### ISSUE THREAD

**Issue by ljharb** [ljharb/String.prototype.matchAll#1]
Some Abstract Operations list arguments as if they were functions, some do not. Which is preferred?

**Comment by ljharb** [comment]
@bterlson @allenwb can one of you weigh in here?

**Comment by bterlson** [comment]
I prefer the notation that lists the arguments as if they were functions. As far as I understand it's just notational. If I am motivated enough I may update all the abstract ops to list the arguments as if they're functions and remove the prose descriptions of arguments.

**Comment by ljharb** [comment]
Perfect, I like that better too. I'll be sure to follow that in my proposals' spec text.
